name: Deploy mdBook

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Install mdBook
        run: cargo install mdbook --vers "^0.4.37" --force

      - name: Build book
        run: mdbook build

      - name: List build output # <--- debug tambahan
        run: |
          echo "Isi folder book/"
          ls -lah book
          echo "Cek apakah ada index.html"
          find book -maxdepth 2 -type f

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./book
